#!/bin/bash

# shellcheck disable=SC1091
source "$(dirname "$0")/src/functions/help"
source "$(dirname "$0")/src/functions/device"
source "$(dirname "$0")/src/functions/status"
source "$(dirname "$0")/src/functions/switch"
source "$(dirname "$0")/src/functions/silence"
source "$(dirname "$0")/src/routes/routesArg"
source "$(dirname "$0")/src/locales/getDictionary"

function main() {
    setup=$(xrandr --prop | devices)

    local opt="$1"
    silence "$@"

    case "$opt" in
    "$ENABLE_ARG")
        switch "$setup" "on" "$SILENT"
        ;;
    "$DISABLE_ARG")
        switch "$setup" "off" "$SILENT"
        ;;
    "$STATUS_ARG")
        status "$setup"
        ;;
    *)
        help
        ;;
    esac
}

main "$@"
