#!/bin/bash

# shellcheck disable=SC1091
source "$(dirname "$0")/src/functions/help"
source "$(dirname "$0")/src/functions/device"
source "$(dirname "$0")/src/functions/status"
source "$(dirname "$0")/src/functions/switch"
source "$(dirname "$0")/src/locales/getDictionary"
source "$(dirname "$0")/src/locales/getSystemLang"

function main() {
    declare -r setup=$(xrandr --prop | devices)

    if [ $# -eq 1 ]; then
        local argument="$1"

        case "$argument" in
        "on")
            switch "$setup" "on"
            ;;
        "off")
            switch "$setup" "off"
            ;;
        "stt")
            status "$setup"
            ;;
        *)
            help
            ;;
        esac
    else
        help
    fi
}

main "$@"
