#!/bin/bash

# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/getSystemLang"

declare -A dictionary=(
    [es_help]="Uso: $INIT [$ENABLE_ARG] [$DISABLE_ARG] [$STATUS_ARG] [$SILENT_ARG]"
    [en_help]="Usage: $INIT [$ENABLE_ARG] [$DISABLE_ARG] [$STATUS_ARG] [$SILENT_ARG]"
)

function print() {
    local action=$1
    lang=$(lang)
    local code="${lang}_${action}"

    echo "${dictionary[$code]}"
}
