#!/bin/bash

# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/getSystemLang"

declare -A dictionary=(
    [es_help]="Uso: $0 [on] [off] [stt]\nOpciones:\n  on\tActiva TearFree\n  off\tDesactiva TearFree\n  stt\tMuestra el estado de TearFree"
    [en_help]="Usage: $0 [on] [off] [stt]\Options:\n  on\tEnable TearFree\n  off\tDisable TearFree\n  stt\tShows TearFree status"
)

function print() {
    local action=$1
    local lang
    lang=$(lang)
    local code="${lang}_${action}"

    printf "%s" "${dictionary[$code]}"
}
