#!/bin/bash

function lang() {
    local lang=${LANG:0:2}
    local available=("es" "en")

    if [[ " ${available[*]} " == *"$lang"* ]]; then
        echo "$lang"
    else
        echo "en"
    fi
}
