#!/bin/bash

readonly LOCAL_DIR="$HOME/.local"
readonly SCRIPT_DIR="$LOCAL_DIR/share/xtearfree"
readonly USER_LOCAL_BIN_DIR="$LOCAL_DIR/bin"

function make_folder() {
  if [ ! -d "$SCRIPT_DIR" ]; then
    mkdir -p "$SCRIPT_DIR"
  fi
}

function install_bin() {
  local bin_file="../bin/fs"
  cp "$bin_file" "$USER_LOCAL_BIN_DIR"
  chmod +x "$USER_LOCAL_BIN_DIR/fs"
}

function install_script() {
  local SRC_DIR="../src"
  local INIT_FILE="../init"
  cp -r "$SRC_DIR" "$SCRIPT_DIR"
  cp -r "$INIT_FILE" "$SCRIPT_DIR"
}

function uninstall() {
  if [ -d "$SCRIPT_DIR" ]; then
    rm -rf "$SCRIPT_DIR"
  fi

  if [ -f "$USER_LOCAL_BIN_DIR/fs" ]; then
    rm "$USER_LOCAL_BIN_DIR/fs"
  fi

  echo "Script uninstalled"
}

function main() {
  if [ "$1" == "--uninstall" ]; then
    uninstall
  else
    make_folder
    install_bin
    install_script
    echo "Script installed"
  fi
}

main "$@"
