#!/bin/bash

readonly OPT_DIR="/opt"
readonly SCRIPT_DIR="$OPT_DIR/xtearfree"

function make_folder() {
  if [ ! -d "$SCRIPT_DIR" ]; then
    sudo mkdir -p "$SCRIPT_DIR"
  fi
}

function install_bin() {
  local binFile="../bin/fs"
  local USR_LOCAL_BIN_DIR="/usr/local/bin"
  sudo cp "$binFile" "$USR_LOCAL_BIN_DIR"
  sudo chmod +x "$USR_LOCAL_BIN_DIR/fs"
}

function install_script() {
  local SRC_DIR="../src"
  local INIT_FILE="../init"
  sudo cp -r "$SRC_DIR" "$SCRIPT_DIR"
  sudo cp -r "$INIT_FILE" "$SCRIPT_DIR"
}

function uninstall() {
  if [ -d "$SCRIPT_DIR" ]; then
    sudo rm -rf "$SCRIPT_DIR"
  fi

  if [ -f "/usr/local/bin/fs" ]; then
    sudo rm "/usr/local/bin/fs"
  fi

  echo "Script uninstalled"
}

function main() {
  if [ "$1" == "--uninstall" ]; then
    uninstall
  else
    make_folder
    install_bin
    install_script
    echo "Script installed"
  fi
}

main "$@"
